### ISSUE TITLE
Coq 8.14 support

### ISSUE THREAD

**Issue by jgrosso** [arthuraa/extructures#14]
Hi! Are there any official plans for Coq 8.14 support?

**Comment by arthuraa** [comment]
Hi! Yes, very much so. In principle everything should be working fine. I'll update the requirements on OPAM as soon as the CI is passing.

**Comment by arthuraa** [comment]
In principle, v0.3.1 should be working with Coq 8.14, and you can get it installed on OPAM. I'll close this for now, but let me know if you have any other issues!
