### ISSUE TITLE
Please add examples and/or a "smoke test" file

### ISSUE THREAD

**Issue by MSoegtropIMC** [arthuraa/extructures#16]
Can you please add a an example? Coq Platform users would appreciate this.

Also Coq Platform has a "smoke test kit", which runs one or more examples from each package included in Coq Platform to test if the package is installed properly. Currently I am just using a file which requires fset from Extructures. A more elaborate test would make sense - it should ideally test as much as possible but run no longer than 10s (on a decent machine).

**Comment by arthuraa** [comment]
Just added one: #18

**Comment by MSoegtropIMC** [comment]
Thanks - a very nice example!
