### ISSUE TITLE
Please create a tag for Coq 8.20 in Coq Platform 2025.01

### ISSUE THREAD

**Issue by MSoegtropIMC** [arthuraa/extructures#34]
The Coq team released Coq `8.20.0` on September 3rd, 2024.
The corresponding Coq Platform release `2025.01` should be released before **Jan 31st, 2025**.
It can be delayed in case of difficulties until Feb 28th, 2025, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.4.0) **does not work** with Coq `8.20.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI appears to test this project, but has some special handling for your project which makes it difficult to retrieve the commit it tests for your project.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.20, **preferably before Dec 31st, 2024**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before Dec 8th, 2024, it will be included in an early Coq Platform beta release of the for Coq 8.20.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.20~2025.01`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.20~2025.01.sh) which already supports Coq version `8.20.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/449

**Comment by arthuraa** [comment]
I have released a new version, `v0.5.0`, and sent a PR to the OPAM archive. As far as I can tell, it is compatible with Coq v8.20.

**Comment by MSoegtropIMC** [comment]
Thank you for the quick action! I will test it as soon as the opam package is merged and then close this issue.

**Comment by MSoegtropIMC** [comment]
Unfortunately it does not work in the context of Coq Platform:
```
# COQC theories/fset.v
# File "./theories/fset.v", line 2, characters 0-106:
# Error: Required library path matches several files in path (found
# /Users/msoegtrop/.opam-current+working-tests/CP.2024.10.1~8.20~2025.01/lib/coq/user-contrib/mathcomp/analysis/homotopy_theory/path.vo and
# /Users/msoegtrop/.opam-current+working-tests/CP.2024.10.1~8.20~2025.01/lib/coq/user-contrib/mathcomp/ssreflect/path.vo).
```
It has been discussed in Zulip that the mathcomp team tries to avoid module name clashes in the future, but for the time being I am afraid you have to give a more explicit name when requiring `path`.

I could patch this on opam level, but I would prefer if you could do a 0.5.1 release.

**Comment by arthuraa** [comment]
What is the easiest way for me to replicate this? I have tried downloading mathcomp 2.2.0 and mathcomp-analysis, but when I require `path`, the mathcomp version takes precedence and no error appears.

**Comment by MSoegtropIMC** [comment]
The method I recommend is to use the Coq Platform scripts from Coq Platform main and create a "full" level opam switch. In essence:
```
git clone git@github.com:coq/platform.git
cd platform
./coq_platform_make.sh

```
The coq platform make script is interactive. Choose level "full" (first question) and the 8.20 pick (second question should be #9 or so). The remaining question are hopefully self explanatory. Don't include CompCert, VST and large packages )just takes time).

Btw.: the issue was introduced in mathcomp 2.3.0 afaik. It shoul dnot happen with 2.2.0.

**Comment by MSoegtropIMC** [comment]
P.S.: the `coq_platform_make.sh` creates a new opam switch - it doesn't touch your existing switches - unless you already have one with the same name which should be unlikely.

**Comment by MSoegtropIMC** [comment]
@arthuraa : the issue should have been fixed by an update of mathcomp-analysis. I will retest v0.5.0.

There is no need for actions from your side.

**Comment by MSoegtropIMC** [comment]
I updated Coq Platform to use coq-extriuctures version 0.5.0 via https://github.com/coq/platform/pull/454 => closing.
