### ISSUE TITLE
Opam

### ISSUE THREAD

**Issue by spitters** [arthuraa/extructures#4]
Would it be possible to do a new release?
http://coq.io/opam/coq-extructures.0.2.2.html
This
"coq-mathcomp-ssreflect" {>= "1.10" & < "1.12~"}
is barring ssr from upgrading.

**Comment by gares** [comment]
Maybe the right place for this bug is https://github.com/arthuraa/extructures CC @arthuraa

**Comment by gares** [comment]
Oops ;-)

**Comment by spitters** [comment]
@arthuraa @gares would addition to Coq platform be the best way to avoid such breakage?

**Comment by arthuraa** [comment]
Thanks for the report, @spitters . I have just sent a PR to the OPAM archive (https://github.com/coq/opam-coq-archive/pull/1582).
