### ISSUE TITLE
Release for Coq 8.13 support

### ISSUE THREAD

**Issue by TheoWinterhalter** [arthuraa/extructures#9]
Hi. We were wondering if a release (on opam) with 8.13 support was coming. I see the `master` branch already supports it.
Thanks! :)

**Comment by arthuraa** [comment]
Thanks for noticing this. I just submitted an update to the OPAM repository. It should be available soon, hopefully.

**Comment by arthuraa** [comment]
It's up!

**Comment by TheoWinterhalter** [comment]
Thanks a lot!
